# Generated by Django 2.1.5 on 2019-07-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
