# Generated by Django 2.1.5 on 2019-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0002_auto_20190812_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='id',
        ),
        migrations.AddField(
            model_name='province',
            name='province_code',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
