# Generated by Django 2.1.5 on 2019-06-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0003_auto_20190630_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
