# Generated by Django 2.1.5 on 2019-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0004_auto_20190812_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
    ]
