# Generated by Django 2.1.5 on 2019-08-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0005_remove_district_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='berberim.Province'),
            preserve_default=False,
        ),
    ]
