# Generated by Django 2.1.5 on 2019-08-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0006_district_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='berberim.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='berberim.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='berberim.Province'),
            preserve_default=False,
        ),
    ]
