# Generated by Django 2.1.5 on 2019-07-07 00:44

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0006_auto_20190706_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
