# Generated by Django 2.1.5 on 2019-08-29 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0007_auto_20190812_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
