# Generated by Django 2.1.5 on 2019-07-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0008_barbershopservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopservices',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='berberim.Barbershop'),
        ),
    ]
