# Generated by Django 2.1.5 on 2019-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0009_auto_20190711_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopservices',
            name='name',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('beardcut', 'Beardcut'), ('hair wash', 'Hair Wash')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
