# Generated by Django 2.1.5 on 2019-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopschedule',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
