# Generated by Django 2.1.5 on 2019-08-30 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0010_barbershopschedule_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='review_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
