# Generated by Django 2.1.5 on 2019-07-11 09:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0010_auto_20190711_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbershopSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Haircut', 'Haircut'), ('Beardcut', 'Beardcut'), ('Hair Wash', 'Hair Wash')], max_length=32), default=list, size=None)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershopschedules', to='berberim.Barbershop')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershopschedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='barbershopservices',
            name='name',
            field=models.CharField(choices=[('Haircut', 'Haircut'), ('Beardcut', 'Beardcut'), ('Hair Wash', 'Hair Wash')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
