# Generated by Django 2.1.5 on 2019-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0011_auto_20190830_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
