# Generated by Django 2.1.5 on 2019-07-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0013_barbershopemployee_barbershop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopemployee',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_employees', to='berberim.Barbershop'),
        ),
    ]
