# Generated by Django 2.1.5 on 2019-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0013_auto_20190901_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
