# Generated by Django 2.1.5 on 2019-10-26 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0014_barbershop_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='review_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
