# Generated by Django 2.1.5 on 2019-07-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0014_auto_20190711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopschedule',
            name='assigned_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='berberim.BarbershopEmployee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbershopemployee',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='berberim.Barbershop'),
        ),
        migrations.AlterField(
            model_name='barbershopschedule',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='berberim.Barbershop'),
        ),
    ]
