# Generated by Django 2.1.5 on 2019-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0015_auto_20190720_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='barbershopemployee',
            name='title',
            field=models.CharField(choices=[('Master', 'Usta'), ('Journeyman', 'Kalfa'), ('Apprentice', 'Çırak')], max_length=30),
        ),
    ]
