# Generated by Django 2.2.7 on 2020-01-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0020_auto_20200131_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='last_updated',
        ),
    ]
