# Generated by Django 2.2.7 on 2020-01-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberim', '0021_remove_service_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershopservice',
            name='name',
        ),
        migrations.AddField(
            model_name='barbershopservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='berberim.Service'),
            preserve_default=False,
        ),
    ]
